import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { loadProfile, CONFIG_DIR } from './controller.mjs';
import { execute } from './process.mjs';
import { listTasks } from './background.mjs';

export async function preflight(profilePath) {
  const profile = loadProfile(profilePath);
  if (Number(process.versions.node.split('.')[0]) < 22) throw new Error('Install Node.js 22 or newer');
  try { fs.accessSync(fileURLToPath(import.meta.resolve('@opencode-ai/plugin'))); }
  catch { throw new Error(`Install plugin dependencies once: cd ${CONFIG_DIR} && npm ci --ignore-scripts`); }
  const versions = [];
  for (const argv of [['git', '--version'], [...profile.opencode, '--version']]) {
    const result = await execute(argv, { timeout: 15 });
    if (result.code !== 0) throw new Error(`Unavailable dependency: ${argv.join(' ')}`);
    versions.push(result.out.trim());
  }
  return { profile, node: process.version, versions, tasks: listTasks(profilePath), commands: path.join(profile.stateRoot, 'commands.log') };
}

export function installLauncher(profilePath) {
  const profile = loadProfile(profilePath), file = path.join(profile.commandCenter, 'start');
  const quote = text => `'${text.replaceAll("'", "'\\''")}'`;
  const script = `#!/bin/sh\n# Command Center launcher, generated by cli.mjs install-launcher.\nset -eu\nCC_START_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)\nexec node "$CC_START_DIR/"${quote(path.relative(profile.commandCenter, path.join(CONFIG_DIR, 'cli.mjs')))} open --profile "$CC_START_DIR/"${quote(path.relative(profile.commandCenter, profile.filename))} "$@"\n`;
  if (fs.existsSync(file) && !fs.readFileSync(file, 'utf8').includes('# Command Center launcher, generated by cli.mjs install-launcher.')) throw new Error(`Existing custom launcher preserved: ${file}`);
  fs.writeFileSync(file, script, { mode: 0o755 }); fs.chmodSync(file, 0o755);
  return file;
}

export async function open(profilePath, { check = false, fresh = false } = {}) {
  const info = await preflight(profilePath), p = info.profile;
  if (check) { console.log(JSON.stringify({ node: info.node, dependencies: info.versions, profile: p.filename, commandCenter: p.commandCenter,
    model: p.models?.builder, tasks: info.tasks.map(task => ({ id: task.id, status: task.status })), commands: info.commands }, null, 2)); return; }
  fs.mkdirSync(p.draftsRoot, { recursive: true });
  fs.mkdirSync(p.stateRoot, { recursive: true, mode: 0o700 });
  const sessionFile = path.join(p.stateRoot, 'interactive-session.json');
  let session;
  if (!fresh && fs.existsSync(sessionFile)) session = JSON.parse(fs.readFileSync(sessionFile)).session;
  console.log(`Command Center: ${p.commandCenter}\n/cc — задачи, подтверждения и восстановление\nКоманды: ${info.commands}`);
  const model = p.models?.builder;
  const argv = [...p.opencode.slice(1), ...(model ? ['--model', model] : []), ...(session ? ['--session', session] : [])];
  const child = spawn(p.opencode[0], argv, { cwd: p.commandCenter, stdio: 'inherit',
    env: { ...process.env, PWD: p.commandCenter, OPENCODE_CONFIG_DIR: CONFIG_DIR, OPENCODE_TUI_CONFIG: path.join(CONFIG_DIR, 'tui.json'), OPENCODE_DISABLE_AUTOUPDATE: 'true',
      CC_PROFILE: p.filename, CC_NODE: process.execPath, CC_WORKER_ROLE: '', CC_WORKER_ROOT: '', CC_WORKER_READ_ROOTS: '', CC_RUN_DIR: '',
      OPENCODE_CONFIG_CONTENT: JSON.stringify({ default_agent: 'planner', share: 'disabled', ...(model ? { model, small_model: model } : {}),
        agent: { planner: { reasoningEffort: p.reasoningEffort?.builder ?? 'low' }, orchestrator: { reasoningEffort: p.reasoningEffort?.builder ?? 'low' } },
        mcp: Object.fromEntries((p.disabledMcp ?? []).map(name => [name, { enabled: false }])) }),
    } });
  // The foreground OpenCode process (and a human terminal command) receives
  // Ctrl+C directly. Keep the supervising Node process alive until it exits.
  const interrupt = () => {};
  process.on('SIGINT', interrupt);
  try { await new Promise((resolve, reject) => { child.once('error', reject); child.once('exit', code => { process.exitCode = code ?? 1; resolve(); }); }); }
  finally { process.removeListener('SIGINT', interrupt); }
}
